#!/bin/sh

commit_msg=$(cat "$1")

pattern="^(feat|fix|refactor|docs|test|chore|build|ci)(\([a-zA-Z0-9._-]+\))?: .+"

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
    echo ""
    echo "Invalid commit message."
    echo ""
    echo "Expected format:"
    echo "  <type>: <description>"
    echo ""
    echo "Allowed types:"
    echo "  feat, fix, refactor, docs, test, chore, build, ci"
    echo ""
    echo "Examples:"
    echo "  feat: add quiz system"
    echo "  fix: correct score calculation"
    echo "  chore: configure Terraform"
    echo ""
    exit 1
fi